import React from 'react';
import { Alert } from 'react-bootstrap';
import { FaRobot, FaInfoCircle } from 'react-icons/fa';
import './styles/AIDisclaimer.css';

/**
 * A reusable component to display an AI-generated content disclaimer
 * @param {Object} props - Component props
 * @param {string} props.variant - Bootstrap Alert variant (default: 'info')
 * @param {string} props.className - Additional CSS classes
 * @param {string} props.message - Custom message (uses default if not provided)
 * @param {boolean} props.showIcon - Whether to show the robot icon (default: true)
 */
//make the ai4cs.in bold
const AIDisclaimer = ({ 
  variant = 'info', 
  className = '', 
  message = 'This output is generated by AI, kindly verify it by legal professional. - (www.ai4cs.in)',
  showIcon = true 
}) => {
  return (
    <Alert 
      variant={variant} 
      className={`ai-disclaimer ${className}`}
    >
      {/* {showIcon && <FaRobot className="ai-disclaimer-icon" />} */}
      <FaInfoCircle className="ai-info-icon" />
      <span className="ai-disclaimer-text">{message}</span>
    </Alert>
  );
};

export default AIDisclaimer;
